### ISSUE TITLE
KeyError: 'suggestions'

### ISSUE THREAD

**Issue by yb3616** [phpactor/ncm2-phpactor#4] opened 2018-08-01 13:32 UTC
![1](https://user-images.githubusercontent.com/8839021/43524553-2a41ffba-95d2-11e8-9816-76f1598de57a.PNG)
![2](https://user-images.githubusercontent.com/8839021/43524564-308c9d30-95d2-11e8-8e73-f379bbad1061.PNG)

**Comment by roxma** [comment] 2018-08-01 14:06
This issue only happens when there's multi byte utf-8 characters.

When chinese characters are present in the buffer. I can get useless completion results using `:set omnifunc=phpactor#Complete` and `<c-x><c-o>`.

It seems this is phpactor issue.

```
<?php

// 姓名

class A
{
  public function foo()
  {
  }
}

$a = new A;
$|<c-x><c-o>
ABDAY_1               m ABDAY_1 = 131072
ABDAY_2               m ABDAY_2 = 131073
ABDAY_3               m ABDAY_3 = 131074
ABDAY_4               m ABDAY_4 = 131075
ABDAY_5               m ABDAY_5 = 131076
ABDAY_6               m ABDAY_6 = 131077
ABDAY_7               m ABDAY_7 = 131078
ABMON_1               m ABMON_1 = 131086
ABMON_10              m ABMON_10 = 131095
ABMON_11              m ABMON_11 = 131096
ABMON_12              m ABMON_12 = 131097
ABMON_2               m ABMON_2 = 131087
ABMON_3               m ABMON_3 = 131088
ABMON_4               m ABMON_4 = 131089
ABMON_5               m ABMON_5 = 131090
ABMON_6               m ABMON_6 = 131091
ABMON_7               m ABMON_7 = 131092
ABMON_8               m ABMON_8 = 131093
ABMON_9               m ABMON_9 = 131094
AF_INET               m AF_INET = 2
AF_INET6              m AF_INET6 = 10
AF_UNIX               m AF_UNIX = 1
ALT_DIGITS            m ALT_DIGITS = 131119
AM_STR                m AM_STR = 131110
ARRAY_FILTER_USE_BOTH m ARRAY_FILTER_USE_BOTH = 1
ARRAY_FILTER_USE_KEY  m ARRAY_FILTER_USE_KEY = 2
ASSERT_ACTIVE         m ASSERT_ACTIVE = 1
ASSERT_BAIL           m ASSERT_BAIL = 3
ASSERT_CALLBACK       m ASSERT_CALLBACK = 2
ASSERT_EXCEPTION      m ASSERT_EXCEPTION = 6
ASSERT_QUIET_EVAL     m ASSERT_QUIET_EVAL = 5
ASSERT_WARNING        m ASSERT_WARNING = 4
```

**Comment by dantleech** [comment] 2018-08-01 14:11
Yep, this is almost certainly a Phpactor issue: https://github.com/phpactor/phpactor/issues/539

**Comment by yb3616** [comment] 2018-08-01 14:12
我要向上游反应情况吗？

**Comment by dantleech** [comment] 2018-08-01 18:59
Have found the [issue](https://github.com/phpactor/completion/pull/12) with Phpactor - not sure if it was the actual cause of the `KeyValue` erorr though.

Would be good, next time, to get the request / response that causes this to happen as [detailed here](https://phpactor.github.io/phpactor/developing.html).

**Comment by roxma** [comment] 2018-08-02 01:28
This issue seems to be fixed after `composer  update phpactor/completion` for the phpactor plugin.

**Comment by yb3616** [comment] 2018-08-02 01:45
@roxma not at all. [#12](https://github.com/phpactor/completion/pull/12#issuecomment-409767751)

**Comment by roxma** [comment] 2018-08-02 01:49
![peek 2018-08-02 09-48](https://user-images.githubusercontent.com/4538941/43557856-46dc5848-9639-11e8-97bb-0d7682da7959.gif)

**Comment by roxma** [comment] 2018-08-02 01:56
![peek 2018-08-02 09-54](https://user-images.githubusercontent.com/4538941/43558078-3cad70a4-963a-11e8-81d8-ee0834820fca.gif)

**Comment by yb3616** [comment] 2018-08-02 01:58
After update phpactor/completion
![6](https://user-images.githubusercontent.com/8839021/43558149-92174902-963a-11e8-81f7-217480e930f8.PNG)
![7](https://user-images.githubusercontent.com/8839021/43558153-9501980c-963a-11e8-9710-923a11cbe3bf.PNG)

**Comment by dantleech** [comment] 2018-08-02 07:29
Hmm, please check you have the correct completion branch:

```
cd ~/.vim/plugged/phpactor/vendor/phpactor/completion # for example
git fetch origin
git reset --hard origin/master
```

```
git log -1
commit ad5f13bacb1bf6d5f8a9e389c6b62ec8b042aec3 (HEAD -> master, composer/master)
Merge: b0dae0a 50138f9
Author: dantleech <dan.t.leech@gmail.com>
Date:   Wed Aug 1 20:07:55 2018 +0100

    Merge pull request #12 from phpactor/byte_offset_not_char_offset
    
    Pass byte-offset to the parser, not the char offset
```

**Comment by yb3616** [comment] 2018-08-02 11:01
@dantleech I'm using neovim with vim-plug, I got no such file ```~/.local/share/nvim/plugged/phpactor/completion```

Here is my branch of ```phpactor```

![9](https://user-images.githubusercontent.com/8839021/43579961-65b04a84-9686-11e8-9e68-a344f6cb227d.PNG)

**Comment by roxma** [comment] 2018-08-02 11:04
> 'm using neovim with vim-plug, I got no such file ~/.local/share/nvim/plugged/phpactor/completion

It's actually `vendor/phpactor/completion` in the `phpactor` plugin directory

**Comment by yb3616** [comment] 2018-08-02 11:06
![10](https://user-images.githubusercontent.com/8839021/43580217-38fdea2c-9687-11e8-9e58-9d5ec9eb1bfa.PNG)

**Comment by yb3616** [comment] 2018-08-02 11:14
![11](https://user-images.githubusercontent.com/8839021/43580514-5187b50e-9688-11e8-81a8-a9015746855e.PNG)
![12](https://user-images.githubusercontent.com/8839021/43580516-51e9d036-9688-11e8-99dd-7e7b04920b1c.PNG)
![13](https://user-images.githubusercontent.com/8839021/43580518-5311a358-9688-11e8-8e96-c5a2a913833d.PNG)
![14](https://user-images.githubusercontent.com/8839021/43580522-54426640-9688-11e8-9cf5-189ce151918a.PNG)

**Comment by dantleech** [comment] 2018-08-02 11:28
that looks correct. can you paste the problem source code here as text?

**Comment by roxma** [comment] 2018-08-02 11:31
I can reproduce using `set omnifunc=phpactor#Complete`

```
<?php

// 姓名

class A
{
  public function foo()
  {
  }
}

$a = new A;
$a->foo();
$a->|<c-x><c-o>
```

**Comment by dantleech** [comment] 2018-08-02 11:40
:+1: yeah. confused. will have another look tonight.

**Comment by dantleech** [comment] 2018-08-02 17:48
Looks like there was some more incorrect assumptions in the completor for class members, should be fixed now: https://github.com/phpactor/completion/pull/13

**Closed** 2018-08-03 00:42 UTC
